### PR TITLE
Bump bindgen and crate versions

### PR DESCRIPTION
**Pull request by ionut-arm**
Signed-off-by: Ionut Mihalcea <ionut.mihalcea@arm.com>

### CODE REVIEW

**Comment by hug-dev** [comment]
Is that only in order to be able to increase the version of the `tss-esapi` crate in Parsec? Would it be possible to increase the `bindgen` version here but use a `git` dependency of this crate wherever needed?

**Comment by ionut-arm** [comment]
How would we be able to publish any dependents, though? I think the whole dependency tree has to be in crates.io before you can publish

**Comment by hug-dev** [comment]
> How would we be able to publish any dependents, though? I think the whole dependency tree has to be in crates.io before you can publish something

Yes, I see if we want to publish `parsec` as a crate on crates.io we will have to do that. Let's see what we decide [for this](https://cloud-native.slack.com/archives/C01EARH2ZB3/p1610526698198400)

**Comment by ionut-arm** [comment]
Updated - we only need to make the service buildable :]

**Review by hug-dev — APPROVED** [review]

**Pull request merged**
